const Theme = {
	palette: {
		type: 'light',
		common: {
			bg: '#f3f3f3',
			white: '#ffffff',
			black: '#000000',
		},
		primary: {
			light: '#00bfff',
			main: '#0099cc',
			dark: '#007399',
			contrastText: '#ffffff',
		},
		secondary: {
			light: '#ff0080',
			main: '#cc0066',
			dark: '#99004d',
			contrastText: '#ffffff',
		},
	},
	shape: {
		brFull: '30rem',
		brCommon: 20,
		brSmall: 14,
	},
	typography: {
		htmlFontSize: 16,
		fontFamily: "'Open Sans', sans-serif",
		fontSize: 14,
		fontWeightLight: 300,
		fontWeightRegular: 400,
		fontWeightMedium: 500,
		fontWeightBold: 700,
		h1: {
			fontFamily: "'Open Sans', sans-serif",
			fontWeight: 500,
			fontSize: 'clamp(15px, 4vw, 22px)',
			lineHeight: 1.167,
			color: '#101f44',
			letterSpacing: '-0.01562em',
			fontStyle: 'normal',
			textTransform: 'normal',
		},
		h2: {
			fontFamily: "'Open Sans', sans-serif",
			fontWeight: 500,
			fontSize: 'clamp(14px, 3vw, 20px)',
			lineHeight: 1.2,
			color: '#101f44',
			letterSpacing: '-0.00833em',
			fontStyle: 'normal',
			textTransform: 'normal',
		},
		h3: {
			fontFamily: "'Open Sans', sans-serif",
			fontWeight: 400,
			fontSize: 'clamp(14px, 3vw, 16px)',
			lineHeight: 1.167,
			color: '#101f44',
			letterSpacing: '0em',
			fontStyle: 'normal',
			textTransform: 'normal',
		},
		h4: {
			fontFamily: "'Open Sans', sans-serif",
			fontWeight: 400,
			fontSize: '1.90rem',
			lineHeight: 1.235,
			color: '#101f44',
			letterSpacing: '0.00735em',
			fontStyle: 'normal',
			textTransform: 'uppercase',
		},
		h5: {
			fontFamily: "'Open Sans', sans-serif",
			fontWeight: 400,
			fontSize: '1.5rem',
			lineHeight: 1.334,
			color: '#101f44',
			letterSpacing: '0em',
			fontStyle: 'normal',
			textTransform: 'uppercase',
		},
		h6: {
			fontFamily: "'Open Sans', sans-serif",
			fontWeight: 400,
			fontSize: '1.25rem',
			lineHeight: 1.6,
			color: '#101f44',
			letterSpacing: '0.0075em',
			fontStyle: 'normal',
			textTransform: 'uppercase',
		},
		subtitle1: {
			fontFamily: "'Open Sans', sans-serif",
			fontWeight: 400,
			fontSize: '1rem',
			lineHeight: 1.75,
			letterSpacing: '0.00938em',
			fontStyle: 'normal',
			textTransform: 'uppercase',
		},
		subtitle2: {
			fontFamily: "'Open Sans', sans-serif",
			fontWeight: 400,
			fontSize: '0.875rem',
			lineHeight: 1.57,
			letterSpacing: '0.00714em',
			fontStyle: 'normal',
			textTransform: 'uppercase',
		},
		body1: {
			fontFamily: "'Open Sans', sans-serif",
			fontWeight: 400,
			fontSize: 'clamp(14px, 2vw, 15px)',
			lineHeight: 1.5,
			letterSpacing: '0.00938em',
			fontStyle: 'normal',
			textTransform: 'none',
		},
		body2: {
			fontFamily: "'Open Sans', sans-serif",
			fontWeight: 400,
			fontSize: 'clamp(10px, 2vw, 12px)',
			lineHeight: 1.43,
			letterSpacing: '0.01071em',
			fontStyle: 'normal',
			textTransform: 'none',
		},
		button: {
			fontFamily: "'Open Sans', sans-serif",
			fontWeight: 400,
			fontSize: 'clamp(14px, 2vw, 15px)',
			lineHeight: 1.5,
			letterSpacing: '0.00938em',
			fontStyle: 'normal',
			textTransform: 'none',
		},
		caption: {
			fontFamily: "'Open Sans', sans-serif",
			fontWeight: 400,
			fontSize: 'clamp(11px, 2vw, 14px)',
			lineHeight: 1.43,
			color: '#616161',
			letterSpacing: '0.01071em',
			fontStyle: 'normal',
			textTransform: 'none',
		},
	},
};

export default Theme;
